format = """
[░▒▓](#a3aed2)\
[  ](bg:#a3aed2 fg:#090c0c)\
$username\
[](bg:#769ff0 fg:#a3aed2)\
$directory\
[](fg:#769ff0 bg:#394260)\
$git_branch\
$git_status\
[](fg:#394260 bg:#212736)\
\n$character"""

[character]
success_symbol = "[❯](bold #00ff00)"

[username]
show_always = true
style_user = "fg:#090c0c bg:#a3aed2"
style_root = "fg:#090c0c bg:#a3aed2"
format = '[ $user ]($style)'

[directory]
style = "fg:#e3e5e5 bg:#769ff0"
format = "[ $path ]($style)"
truncation_length = 1000
truncate_to_repo = false

[git_branch]
symbol = ""
style = "bg:#394260"
format = '[[ $symbol $branch ](fg:#769ff0 bg:#394260)]($style)'

[git_status]
style = "bg:#394260"
format = '[[ ($all_status$ahead_behind) ](fg:#769ff0 bg:#394260)]($style)'
